- name: Install postgresql as root
  hosts: node1, node2
  become: yes
  become_user: root
  tasks:
    - name: Install postgresql
      yum:
        name: postgresql
        state: latest
    - name: Install postgresql-server
      yum:
        name: postgresql-server
        state: latest
    - name: Install postgresql-contrib
      yum:
        name: postgresql-contrib
        state: latest
    - name: Install postgresql-libs
      yum:
        name: postgresql-libs
        state: latest
    - name: Start postgresql
      service: name=postgresql state=restarted enabled=yes
  handlers:
    - name: shell
      shell: ls -la
      register: shell_result
    - name: debug
      debug:
        var: shell_result.stdout_lines

        
    # - name: Create user
    #   postgresql_user:
    #     name: "jelena-dokic"
    #     password: "test"
    #     encrypted: True
    #   become_user: postgres
    # - name: Create db
    #   postgresql_db:
    #     name: "psql-db"
    #     owner: "jelena-dokic"
    #     template: template0
    #     encoding: UTF8
    #     lc_collate: 'en_US.UTF-8'
    #     lc_ctype: 'en_US.UTF-8'
    #   become_user: postgres


    # - name: shell
    #   shell: ls -la
    #   register: shell_result
    # - name: debug
    #   debug:
    #     var: shell_result.stdout_lines