- name: Install postgresql as root
  hosts: node1, node2
  become: yes
  become_user: root
  tasks:
    - name: Install postgresql
      yum:
        name: postgresql
        state: latest
    - name: Install postgresql-server
      yum:
        name: postgresql-server
        state: latest
    - name: Install postgresql-contrib
      yum:
        name: postgresql-contrib
        state: latest
    - name: Install postgresql-libs
      yum:
        name: postgresql-libs
        state: latest
    - name: Start postgresql
      service: name=postgresql state=restarted enabled=yes
    - name: shell
      shell: sudo postgresql-setup initdb
      register: shell_result
      ignore_errors: yes


    # - name: shell
    #   shell: ls -la
    #   register: shell_result
    # - name: debug
    #   debug:
    #     var: shell_result.stdout_lines