- hosts: node1, node2
  become: yes
  become_user: root
  tasks:
    - name: Ensure nginx is at the latest version
      yum: 
        name: nginx
        state: latest
    - name: Stop apache
      service: 
        name: httpd
        state: stopped
    - name: Start and Enable nginx
      service: 
        name: nginx
        state: started
        enabled: yes
    - name: Copy nginx.conf
      copy: 
        src: nginx/nginx.conf
        dest: /etc/nginx/conf.d/ansible.conf
      notify:
        - Restart nginx
    - name: Copy index.html file
      copy: 
        src: nginx/index.html
        dest: /srv/http/
      notify:
      - Restart nginx
  handlers:
    - name: Restart nginx
      service: 
        name: nginx
        state: restarted